#!/bin/bash

########################################################################################################################
# BEFORE BOOTSTRAP
#
# * Install 'yadm'
# * Install 'sudo' and configure for the user.
########################################################################################################################

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Init submodules..."
yadm submodule update --recursive --init

if [ -e /etc/gentoo-release ]; then
    echo "Cloning my portage repository..."
    cd /usr/local
    sudo mkdir portage
    sudo chown $USER:$USER portage
    git clone https://github.com/richiware/richioverlay.git portage
    cd portage
    git pull --ff-only
    cd ~
    sudo cp ~/.config/yadm/system/richioverlay.conf /etc/portage/repos.conf/
fi

echo "Installing packages..."
if [ -e /etc/gentoo-release ]; then
    sudo emerge -vau \
        `: # A cat clone with syntax highlighting, Git integration, so on.` \
        bat \
        `: # A host application for browserpass browser extension providing it access to your password store.` \
        browserpass \
        `: # fast compiler cache.` \
        ccache \
        `: # C/C++/ObjC language server supporting cross references, hierarchies, ... Used by CoC Vim plugin.` \
        ccls \
        `: # Exuberant Ctags creates tags files for code browsing in editors.` \
        ctags \
        `: # DejaVu fonts, bitstream vera with ISO-8859-2 characters. For interface fonts.` \
        dejavu \
        `: # GUI for GPaste clipboard manager for Gnome Shell.` \
        draobpilc \
        `: # eselect plugin for adding repositories into your portage.` \
        eselect-repository \
        `: # A simple, fast and user-friendly alternative to find.` \
        fd \
        `: # Fuzzy-finder.` \
        fzf \
        `: # Wrapper around PyFlakes, pep8 and mccabe. Needed by coc-python Vim plugin.` \
        flake8 \
        `: # Adds KStatusNotifierItem support to the Shell.` \
        gnome-shell-extension-appindicator \
        `: # A password manager for the command line written in Go.` \
        gopass \
        `: # Clipboard management system.` \
        gpaste \
        `: # Command-line tool for adding icons to filenames.` \
        izer \
        `: # A lightweight and flexible command-line JSON processor.` \
        jq \
        `: # A modern, hackable, featureful, OpenGL-based terminal emulator.` \
        kitty \
        `: # Little Brother database. Used by coc-lbdbq Vim plugin.` \
        lbdb \
        `: # A Helvetica/Times/Courier replacement TrueType font set, courtesy of Red Hat. For documents` \
        liberation-fonts \
        neovim \
        `: # NetworkManager OpenVPN plugin` \
        networkmanager-openvpn \
        `: # Statusline/prompt utility` \
        powerline-taskwarrior \
        `: # OpenType Unicode font with symbols for Powerline/Airline.` \
        powerline-symbols \
        `: # Python client for Neovim` \
        pynvim \
        `: # Impl of the Language Server Protocol for Python. Needed by coc-python Vim plugin.` \
        python-language-server \
        `: # A vim-inspired file manager for the console.` \
        ranger \
        `: # Recursively searches directories for a regex pattern.` \
        ripgrep \
        `: # Taskwarrior is a command-line todo list manager.` \
        task \
        `: # Taskwarrior <-> Google Calendar sync.` \
        taskw_gcal_sync \
        `: # A code-searching tool similar to ack, but faster.` \
        the_silver_searcher \
        `: # Magnificent app which corrects your previous console command.` \
        thefuck \
        `: # Tracks your time from the command line, and generates reports.` \
        timew \
        `: # Terminal multiplexer.` \
        tmux \
        `: # Online command-line translator. Used by VicentCordobes/vim-translate Vim plugin.` \
        translate-shell \
        `: # Lists directories recusively, and produces an indented listing of files.` \
        app-text/tree \
        `: # C/C++/C#/D/Java/Pawn code indenter and beautifier.` \
        uncrustify \
        `: # Draw images on terminals by using child windows. Usec by ranger.` \
        ueberzug \
        `: # NodeJS dependency management. Used to install iamcco/markdown-preview.nvim Vim plugin.` \
        yarn \
        `: # A highly customizable and functional document viewer` \
        zathura-meta zathura-pdf-mupdf \
        zsh

    sudo emerge -vau --oneshot \
        `: # Used by openweather gnome shell extension.` \
        zip
elif [ -e /etc/os-release ]; then
    source /etc/os-release
    case $NAME in
        "Ubuntu")
            apt -y install \
                bat \
                ccls \
                exuberant-ctags \
                fd-find \
                flake8 \
                fonts-dejavu \
                fonts-liberation2 \
                fonts-powerline \
                fzf \
                gopass \
                gpaste \
                kitty \
                lbdb \
                neovim \
                powerline \
                python3-neovim \
                python3-powerline-taskwarrior \
                ranger \
                ripgrep \
                silversearcher-ag \
                taskwarrior \
                timewarrior \
                tmux \
                translate-shell \
                tree \
                uncrustify \
                yarnpkg \
                zathura \
                zsh
            pip3 install \
                draobpilc \
                python-language-server \
                thefuck \
                ueberzug
            go get -u github.com/NightWolf007/izer
            ;;
    esac
fi

# Install git-foresta
curl -L https://github.com/takaaki-kasai/git-foresta/raw/master/git-foresta -o ~/.local/bin/git-foresta && chmod +x ~/.local/bin/git-foresta

# Installing zsh
sudo usermod --shell /bin/zsh ricardo

echo "Creating links..."

# Neovim/Vim
## Coc settings
mkdir -p ~/.config/nvim
ln -s ~/.vim/init.vim ~/.config/nvim/init.vim
ln -s ~/.vim/coc-settings.json ~/.config/nvim/coc-settings.json

# Gnome shell extensions' links
ln -s ~/.local/share/gnome-shell/extensions/relative-repos/taskwhisperer-extension@infinicode.de/taskwhisperer-extension@infinicode.de ~/.local/share/gnome-shell/extensions/
ln -s ~/.local/share/gnome-shell/extensions/relative-repos/randomwallpaper@iflow.space/randomwallpaper@iflow.space ~/.local/share/gnome-shell/extensions/
ln -s ~/.local/share/gnome-shell/extensions/relative-repos/gnome-shell-extension-mpris-indicator-button/mprisindicatorbutton@JasonLG1979.github.io ~/.local/share/gnome-shell/extensions/
cd ~/.local/share/gnome-shell/extensions/relative-repos/gnome-shell-extension-openweather && ./autogen.sh && make local-install; cd ~

echo "Configuring CCache..."
sudo cp ~/.config/yadm/system/tmpfs-ccache /etc/
sudo cp ~/.config/yadm/system/tmpfs-ccache.service /etc/systemd/system/
sudo cp ~/.config/yadm/system/tmpfs-ccache-service.sh /usr/local/bin/
sudo systemctl daemon-reload
sudo systemctl enable tmpfs-ccache

echo "Installing fonts..."
# Powerline symbols
sudo eselect fontconfig enable 10-powerline-symbols.conf
# DevIcons
mkdir -p ~/.local/share/fonts/Inconsolata\ Nerd\ Font
cd ~/.local/share/fonts/Inconsolata\ Nerd\ Font
wget https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Inconsolata/complete/Inconsolata%20Regular%20Nerd%20Font%20Complete.ttf
fc-cache -f -v
cd -

echo "Installing Gnome settings..."
~/.config/gnome-terminal-colors-solarized/install.sh --scheme dark --profile Solarized --install-dircolors
dconf write "/org/gnome/desktop/wm/preferences/titlebar-font" "'DejaVu Sans Bold Semi-Condensed 9'"
dconf write "/org/gnome/desktop/wm/preferences/button-layout" "'appmenu:minimize,close'"
dconf write "/org/gnome/desktop/interface/document-font-name" "'Liberation Sans 9'"
dconf write "/org/gnome/desktop/interface/font-name" "'DejaVu Sans Semi-Condensed 9'"
dconf write "/org/gnome/desktop/interface/gtk-theme" "'Adwaita-dark'"
dconf write "/org/gnome/desktop/interface/monospace-font-name" "'Inconsolata Nerd Font 10'"
dconf write "/org/gnome/shell/overrides/workspaces-only-on-primary" "true"
dconf write "org.gnome.shell disable-extension-version-validation" "true"
gnome-shell-extension-tool -e 'openweather-extension@jenslody.de'
gnome-shell-extension-tool -e 'github.notifications@alexandre.dufournet.gmail.com'
gnome-shell-extension-tool -e 'tracker-search-provider@sinnix.de'
gnome-shell-extension-tool -e 'gistnotes@mohan43u.gmail.com'
gnome-shell-extension-tool -e 'windowsNavigator@gnome-shell-extensions.gcampax.github.com'
gnome-shell-extension-tool -e 'vim-key-mapping@richiware.github.com'
gnome-shell-extension-tool -e 'randomwallpaper@iflow.space'
gnome-shell-extension-tool -e 'remove-dropdown-arrows@mpdeimos.com'
gnome-shell-extension-tool -e 'text_translator@awamper.gmail.com'
gnome-shell-extension-tool -e 'taskwhisperer-extension@infinicode.de'
gnome-shell-extension-tool -e 'timewarrior-indicator@natsakis.com'
gnome-shell-extension-tool -e 'mprisindicatorbutton@JasonLG1979.github.io'
gnome-shell-extension-tool -e 'gnome-stats-pro@thrallingpenguin.com'

echo "Configuring NeoVim..."
nvim -c 'call dein#install()' -c 'CocInstall coc-python coc-emoji coc-highlight coc-lbdbq coc-tag'

echo "Last manual configuration..."
echo "    - Install firefox plugins."

# TODO: add my user to groups
