#!/bin/bash

########################################################################################################################
# BEFORE BOOTSTRAP
#
# * Install 'yadm'
# * Install 'sudo' and configure for the user.
########################################################################################################################

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Init submodules..."
yadm submodule update --recursive --init

if [ -e /etc/gentoo-release ]; then
    echo "Cloning my portage repository..."
    cd /usr/local
    sudo mkdir portage
    sudo chown $USER:$USER portage
    git clone https://github.com/richiware/richioverlay.git portage
    cd ~
    sudo cp ~/.yadm/system/richioverlay.conf /etc/portage/repos.conf/
fi

echo "Installing packages..."
if [ -e /etc/gentoo-release ]; then
    sudo emerge -vau \
        `: # C/C++/ObjC language server supporting cross references, hierarchies, ... Used by CoC Vim plugin.` \
        ccls \
        `: # Exuberant Ctags creates tags files for code browsing in editors.` \
        ctags \
        `: # DejaVu fonts, bitstream vera with ISO-8859-2 characters. For interface fonts.` \
        dejavu \
        `: # eselect plugin for adding repositories into your portage.` \
        eselect-repository \
        `: # Wrapper around PyFlakes, pep8 and mccabe. Needed by coc-python Vim plugin.` \
        flake8 \
        `: #A sans-serif monotype font for code listings. For monospace.` \
        inconsolata \
        `: # A lightweight and flexible command-line JSON processor.` \
        jq \
        `: # Little Brother database. Used by coc-lbdbq Vim plugin.` \
        lbdb \
        `: # A Helvetica/Times/Courier replacement TrueType font set, courtesy of Red Hat. For documents` \
        liberation-fonts \
        neovim \
        `: # Statusline/prompt utility` \
        app-shells/powerline \
        `: # OpenType Unicode font with symbols for Powerline/Airline.` \
        powerline-symbols \
        `: # Python client for Neovim` \
        pynvim \
        `: # Impl of the Language Server Protocol for Python. Needed by coc-python Vim plugin.` \
        python-language-server \
        `: # A vim-inspired file manager for the console.` \
        ranger \
        `: # Taskwarrior is a command-line todo list manager.` \
        task \
        `: # A code-searching tool similar to ack, but faster.` \
        the_silver_searcher \
        `: # Magnificent app which corrects your previous console command.` \
        thefuck \
        `: # Tracks your time from the command line, and generates reports.` \
        timew \
        `: # Terminal multiplexer.` \
        tmux \
        `: # Online command-line translator. Used by VicentCordobes/vim-translate Vim plugin.` \
        translate-shell \
        `: # Lists directories recusively, and produces an indented listing of files.` \
        app-text/tree \
        `: # Draw images on terminals by using child windows. Usec by ranger.` \
        ueberzug \
        `: # NodeJS dependency management. Used to install iamcco/markdown-preview.nvim Vim plugin.` \
        yarn \
        `: # A highly customizable and functional document viewer` \
        zathura \
        zsh
elif [ -e /etc/os-release ]; then
    source /etc/os-release
    case $NAME in
        "Ubuntu")
            apt -y install \
                ccls \
                exuberant-ctags \
                flake8 \
                fonts-dejavu \
                fonts-inconsolata \
                fonts-liberation2 \
                fonts-powerline \
                lbdb \
                neovim \
                powerline \
                python3-neovim \
                ranger \
                silversearcher-ag \
                taskwarrior \
                timewarrior \
                tmux \
                translate-shell \
                tree \
                yarnpkg \
                zathura \
                zsh
            pip3 install python-language-server thefuck ueberzug
            ;;
    esac
fi

# Install git-foresta
curl -L https://github.com/takaaki-kasai/git-foresta/raw/master/git-foresta -o ~/.local/bin/git-foresta && chmod +x ~/.local/bin/git-foresta

# Installing zsh
sudo usermod --shell /bin/zsh ricardo

echo "Creating links..."

# Neovim/Vim
## Coc settings
mkdir -p ~/.config/nvim
ln -s ~/.vim/init.vim ~/.config/nvim/init.vim
ln -s ~/.vim/coc-settings.json ~/.config/nvim/coc-settings.json

# Gnome shell extensions' links
ln -s ~/.local/share/gnome-shell/extensions/relative-repos/taskwhisperer-extension@infinicode.de/taskwhisperer-extension@infinicode.de ~/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de
ln -s ~/.local/share/gnome-shell/extensions/relative-repos/randomwallpaper@iflow.space/randomwallpaper@iflow.space ~/.local/share/gnome-shell/extensions/randomwallpaper@iflow.space
ln -s ~/.local/share/gnome-shell/extensions/relative-repos/gnome-shell-extension-mpris-indicator-button/mprisindicatorbutton@JasonLG1979.github.io ~/.local/share/gnome-shell/extensions/mprisindicatorbutton@JasonLG1979.github.io
cd ~/.local/share/gnome-shell/extensions/relative-repos/gnome-shell-extension-openweather && ./autogen.sh && make local-install; cd ~

echo "Configuring CCache..."
sudo cp ~/.yadm/system/tmpfs-ccache /etc/
sudo cp ~/.yadm/system/tmpfs-ccache.service /etc/systemd/system/
sudo cp ~/.yadm/system/tmpfs-ccache-service.sh /usr/local/bin/
sudo systemctl daemon-reload
sudo systemctl enable tmpfs-ccache

echo "Installing powerline fonts..."
sudo eselect fontconfig enable 10-powerline-symbols.conf

echo "Installing Gnome settings..."
~/.config/gnome-terminal-colors-solarized/install.sh --scheme dark --profile Solarized --install-dircolors
dconf write "/org/gnome/desktop/wm/preferences/titlebar-font" "'DejaVu Sans Bold Semi-Condensed 9'"
dconf write "/org/gnome/desktop/wm/preferences/button-layout" "'appmenu:minimize,close'"
dconf write "/org/gnome/desktop/interface/document-font-name" "'Liberation Sans 9'"
dconf write "/org/gnome/desktop/interface/font-name" "'DejaVu Sans Semi-Condensed 9'"
dconf write "/org/gnome/desktop/interface/gtk-theme" "'Adwaita-dark'"
dconf write "/org/gnome/desktop/interface/monospace-font-name" "'Inconsolata 10'"
dconf write "/org/gnome/shell/overrides/workspaces-only-on-primary" "true"
gnome-shell-extension-tool -e 'openweather-extension@jenslody.de'
gnome-shell-extension-tool -e 'github.notifications@alexandre.dufournet.gmail.com'
gnome-shell-extension-tool -e 'suspend-button@laserb'
gnome-shell-extension-tool -e 'tracker-search-provider@sinnix.de'
gnome-shell-extension-tool -e 'gistnotes@mohan43u.gmail.com'
gnome-shell-extension-tool -e 'windowsNavigator@gnome-shell-extensions.gcampax.github.com'
gnome-shell-extension-tool -e 'vim-key-mapping@richiware.github.com'
gnome-shell-extension-tool -e 'randomwallpaper@iflow.space'
gnome-shell-extension-tool -e 'remove-dropdown-arrows@mpdeimos.com'
gnome-shell-extension-tool -e 'text_translator@awamper.gmail.com'
gnome-shell-extension-tool -e 'taskwhisperer-extension@infinicode.de'
gnome-shell-extension-tool -e 'timewarrior-indicator@natsakis.com'
gnome-shell-extension-tool -e 'mprisindicatorbutton@JasonLG1979.github.io'
gnome-shell-extension-tool -e 'gnome-stats-pro@thrallingpenguin.com'

echo "Configuring NeoVim..."
nvim -c 'call dein#install()' -c 'CocInstall coc-python coc-emoji coc-highlight coc-lbdbq coc-tag'
